project:
  type: website
  preview:
    port: 1414
  output-dir: _build
  render:
    # List index.qmd first so that / redirects to it instead of components.html.
    - /index.qmd
    - /*.qmd
    - components
    - inputs
    - outputs
    - display-messages
    - docs
    - development
    - gallery
    - api
  resources:
    - /pypi/**
    - /robots.txt
    - objects.json
    - "*.png"
    - "*.gif"
    - "*.jpg"
    - "*.svg"
  post-render:
    - scripts/post-render.py

metadata-files:
  - api/_sidebar.yml

filters:
  - shinylive
  - interlinks

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/

website:
  title: "Shiny for Python"
  page-navigation: true
  favicon: "favicon.png"
  open-graph:
    site-name: Shiny for Python
    locale: es_ES
    image: https://shiny.posit.co/py/images/shiny-for-python.jpg
    description: Build interactive web applications easily with the power of Python’s data and scientific stack.
  twitter-card:
    title: "Shiny for Python"
    description: "Build interactive web applications easily with the power of Python’s data and scientific stack."
    image: https://shiny.posit.co/py/images/shiny-for-python.jpg
    image-width: 1200
    image-height: 630
    card-style: "summary_large_image"

  navbar:
    background: primary
    foreground: light
    logo: shiny-for-python.svg
    logo-alt: The logo for Shiny for Python
    search: true
    left:
      - text: "Learn Shiny"
        file: docs/quick-start.qmd
      - text: "Deploy"
        menu:
          - docs/deploy-cloud.qmd
          - docs/deploy-on-prem.qmd
          - docs/shinylive.qmd
      - text: "Components"
        file: components/index.qmd
      - text: "Gallery"
        file: gallery/index.qmd
      - text: "Examples"
        href: https://shinylive.io/py/examples/
        target: _blank
      - text: "Function Reference"
        href: api/index.qmd
    tools:
      - icon: discord
        href: https://discord.gg/yMGCamUMnS
        text: Shiny Discord
      - icon: github
        href: https://github.com/posit-dev/py-shiny/
        text: Shiny for Python Github

  page-footer:
    left: 'Proudly supported by <a href="https://www.posit.co/" class="no-icon"><img src="/images/posit-logo-black.svg" alt="Posit" width="80" style="padding-left: 3px;vertical-align:text-top;"></a>'
    right:
      - icon: discord
        href: https://discord.gg/yMGCamUMnS
        aria-label: Shiny Discord
      - icon: github
        href: https://github.com/posit-dev/py-shiny/
        aria-label: Shiny for Python Github
      - icon: twitter
        href: https://twitter.com/posit_pbc
        aria-label: Posit Twitter
      - icon: youtube
        href: https://www.youtube.com/playlist?list=PL9HYL-VRX0oRbLoj3FyL5zeASU5FMDgVe
        aria-label: Shiny YouTube Playlist

  sidebar:
    - id: components
      collapse-level: 2
      contents:
        - text: "![](/images/blank-pixel.png){.sidebar-title}__COMPONENTS__"
          href: components/
        - section: "![](/images/sliders.svg){.sidebar-icon .sidebar-subtitle}__Inputs__"
          contents:
            - components/inputs/action-button.qmd
            - components/inputs/action-link.qmd
            - components/inputs/checkbox.qmd
            - components/inputs/checkbox-group.qmd
            - components/inputs/date-range-selector.qmd
            - components/inputs/date-selector.qmd
            - components/inputs/numeric-input.qmd
            - components/inputs/password-field.qmd
            - components/inputs/radio-buttons.qmd
            - components/inputs/select-single.qmd
            - components/inputs/select-multiple.qmd
            - components/inputs/selectize-single.qmd
            - components/inputs/selectize-multiple.qmd
            - components/inputs/slider.qmd
            - components/inputs/slider-range.qmd
            - components/inputs/switch.qmd
            - components/inputs/text-area.qmd
            - components/inputs/text-box.qmd
        - section: "![](/images/bar-chart-line-fill.svg){.sidebar-icon .sidebar-subtitle}__Outputs__"
          contents:
            - components/outputs/data-grid.qmd
            - components/outputs/datatable.qmd
            - components/outputs/image.qmd
            - components/outputs/map-ipyleaflet.qmd
            - components/outputs/plot-matplotlib.qmd
            - components/outputs/plot-plotly.qmd
            - components/outputs/plot-seaborn.qmd
            - components/outputs/text.qmd
            - components/outputs/ui.qmd
            - components/outputs/value-box.qmd
            - components/outputs/verbatim-text.qmd
        - section: "![](/images/chat-dots-fill.svg){.sidebar-icon .sidebar-subtitle}__Display Messages__"
          contents:
            - components/display-messages/modal.qmd
            - components/display-messages/notifications.qmd
            - components/display-messages/progress-bar.qmd
            - components/display-messages/tooltips.qmd

    - id: docs
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Get Started"
          contents:
            - docs/quick-start.qmd
            - docs/dashboards.qmd
            - docs/jupyter-widgets.qmd
        - section: "Workflow"
          contents:
            - docs/install-create-run.qmd
            - docs/debug.qmd
        - section: "Reactivity"
          contents:
            - docs/reactive-foundations.qmd
            - docs/reactive-patterns.qmd
            - docs/reactive-mutable.qmd
        - section: "User interfaces"
          contents:
            - docs/ui-components.qmd
            - docs/ui-dynamic.qmd
            - docs/ui-html.qmd
            - docs/ui-customize.qmd
        - section: "Express vs Core"
          contents:
            - docs/express-motivation.qmd
            - docs/express-difference.qmd
        - section: "Modules"
          contents:
            - docs/modules.qmd
            - docs/module-communication.qmd
        - section: "Extending"
          contents:
            - docs/custom-component-one-off.qmd
            - docs/custom-components-pkg.qmd
        - section: "Framework Comparisons"
          contents:
            - docs/comp-streamlit.qmd
            - docs/comp-r-shiny.qmd
        - section: "Miscellaneous"
          contents:
            - docs/routing.qmd
    # TODO: if the sidebar only has 1 entry, then it displays for the entire site...
    # added entry below to prevent this.
    - id: deploy

format:
  html:
    # it appears that these are applied to all rendered pages, and _metadata.yml
    # in a subdirectory would e.g. add an additional css file (not override the one here)
    # see _metadata.yml for options meant to be overridden in subdirectories.
    toc: true
    theme: quarto-style.scss
    include-before-body: include-before-body.html
    include-in-header: include-in-header.html
    code-copy: true
    link-external-newwindow: true
    grid:
      sidebar-width: 300px
      gutter-width: 2.5rem

editor:
  markdown:
    wrap: sentence
